global:
  scrape_interval: 5s # Poll every 5 seconds (Fast for testing!)

scrape_configs:
  - job_name: 'event-platform'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        # Use the Docker Service Names defined in docker-compose.yml
        - 'apigateway:8080'
        - 'userservice:8084'
        - 'eventservice:8081'
        - 'bookingservice:8083'
        - 'notificationservice:8085' # Make sure this matches your property file port!